language: java
jdk: openjdk7

before_install:
    - git submodule init
    - git submodule update
    - echo "libs_path=." > gradle.properties
    - wget https://www.dropbox.com/sh/0aqvalqobu61t44/AADiG9psYrYuZncFcXzsnfm2a/BloodMagic-1.7.10-1.3.1-7-deobf.jar?dl=1 -O BloodMagic-1.7.10-1.3.1-7-deobf.jar
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
